### ISSUE TITLE
Discord <-> Matrix/XMPP bridge

### ISSUE THREAD

**Issue by hyperak** [TheMrIron2/Project-Lylat#1]
haha I do not have a Discord account anymore so it would be highly gamer if we could bridge a Matrix Room and a XMPP MUC with the general chat on your guild `:)`

just give me a bot token and I'll set it up

```thanks```

**Comment by yeah-its-gloria** [comment]
And how are we supposed to give you a token without, you know, anyone else `yoink`-ing it?

**Comment by hyperak** [comment]
Ah, right, I guess you didn't catch my contact info when I deleted my account lol

just uhh mail me at diego@dieg.io or XMPP `xmpp best protocol`

**Comment by yeah-its-gloria** [comment]
Not sure about XMPP (alone) but I've got nothing against a Matrix room - have you created one yet?

**Comment by hyperak** [comment]
Yeah, my idea is bridge Discord with both of them.

I just made an MUC and a room:

lylat-general@rooms.dieg.io
and
#lylat-general:fuwafuwa.space

**Comment by hyperak** [comment]
They are both running now.
